---
default:
  tags:
    - docker

include:
  - project: "ics-infrastructure/gitlab-ci-yml"
    file: "PreCommit.gitlab-ci.yml"

stages: [check, deploy]

run-pre-commit:
  script:
    - pre-commit run trailing-whitespace
    - pre-commit run end-of-file-fixer
    - pre-commit run check-yaml
    - pre-commit run check-added-large-files

run markdown lint:
  stage: check
  image: pipelinecomponents/markdownlint:latest
  script:
    - mdl --config .mdlrc .

pages:
  stage: deploy
  image: registry.esss.lu.se/ics-docker/sphinx
  script:
    - sphinx-build -M html src build
    - mv build/html public
  artifacts:
    paths:
      - public
  only:
    - master
