---
default:
  tags:
    - docker

include:
  - project: "ics-infrastructure/gitlab-ci-yml"
    file: "PreCommit.gitlab-ci.yml"

stages: [check, build, deploy]

build:
  stage: build
  image: registry.esss.lu.se/ics-docker/sphinx
  script:
    - sphinx-build -M html src build -W --keep-going
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  script:
    - mv build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
