---
name: Docs

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.11"
      - uses: pre-commit/action@v3.0.1

  build:
    runs-on: ubuntu-latest
    defaults:
      # This is necessary due to the use of the setup-miniconda action below. See their documentation
      # at https://github.com/conda-incubator/setup-miniconda#usage-examples
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"
      - uses: conda-incubator/setup-miniconda@v4
        with:
          environment-file: environment.yml
      - run: sphinx-build -M html src build -W --keep-going
      - uses: actions/upload-pages-artifact@v5
        with:
          path: build/html

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
